#import "../_fragments/Students.gql"

query students {
  students {
    _id
    isPublic
    title
    cover {
      url
      public_id
    }
    updatedAt
    createdAt
  }
}

query editStudent($_id: String) {
  student(_id: $_id) {
    ...StudentAttributes
  }
}

query student($_id: String, $sortBy: String) {
  student(_id: $_id) {
    ...StudentAttributes
    comments(sortBy: $sortBy) {
      _id
      comment
      createdAt
      user {
        _id
        name {
          first
          last
        }
      }
    }
  }
}
