#import "../_fragments/Students.gql"

query students {
  students {
    _id
    code
    givenName
    familyName
    updatedAt
    createdAt
  }
}

query editStudent($_id: String) {
  student(_id: $_id) {
    ...StudentAttributes
  }
}

query student($_id: String, $sortBy: String) {
  student(_id: $_id) {
    ...StudentAttributes
  }
}
